config/routes.rb
Parcel::Application.routes.draw do

  match 'auth/:provider/callback', to: 'authentications#create'
  match 'auth/failure', to: redirect('/')
  match 'signout', to: 'authentications#destroy', as: 'signout'

  resources :gardens

  root :to => 'gardens#index'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  def initialize(user)
    can [:update, :destroy], Garden, :user_id => user.id
  end
end

app/models/garden.rb
class Garden
  include Mongoid::Document
  include Mongoid::Timestamps
  include Gmaps4rails::ActsAsGmappable

  before_validation(:on => :update) do
    self.gmaps = !address_changed?
    true
  end

  acts_as_gmappable :address => :address, :position => :position, :callback => :save_neighborhood

  field :title,        type: String
  field :description,  type: String
  field :address,      type: String
  field :neighborhood, type: String
  field :position,     type: Array
  field :gmaps,        type: Boolean

  belongs_to :user

  def save_neighborhood(data)
    data["address_components"].each do |c|
      if c["types"].include? "neighborhood"
        self.neighborhood = c["long_name"]
      end
    end
  end
end

app/models/user.rb
class User
  include Mongoid::Document
  field :provider,         type: String
  field :uid,              type: String
  field :first_name,       type: String
  field :email,            type: String
  field :image,            type: String
  field :oauth_token,      type: String
  field :oauth_expires_at, type: Time

  attr_protected :provider, :uid, :first_name, :email, :image, :oauth_token, :oauth_expires_at

  has_many :gardens

  def self.from_omniauth(auth)
    user = where(auth.slice(:provider, :uid))
    return user.first unless user.blank?

    self.new do |user|
      user.provider         = auth.provider
      user.uid              = auth.uid
      user.first_name       = auth.info.first_name
      user.email            = auth.info.email
      user.image            = auth.info.image
      user.oauth_token      = auth.credentials.token
      user.oauth_expires_at = Time.at(auth.credentials.expires_at)
      user.save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  helper_method :current_user
  helper_method :user_signed_in?
  helper_method :correct_user?

  private
    def current_user
      begin
        @current_user ||= User.find(session[:user_id]) if session[:user_id]
      rescue Mongoid::Errors::DocumentNotFound
        nil
      end
    end

    def user_signed_in?
      return true if current_user
    end

    def correct_user?
      @user = Garden.find(params[:id]).user
      unless current_user == @user
        redirect_to root_url, :alert => "Access denied."
      end
    end

    def authenticate_user!
      if !current_user
        redirect_to root_url, :alert => 'You need to sign in for access to this page.'
      end
    end
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]

  # GET /gardens
  # GET /gardens.json
  def index
    @gardens = Garden.all
    @json = Garden.all.to_gmaps4rails do |garden, marker|
      marker.json({ :id => garden.id })
    end

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @gardens }
    end
  end

  # GET /gardens/1
  # GET /gardens/1.json
  def show
    @garden = Garden.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @garden }
    end
  end

  # GET /gardens/new
  # GET /gardens/new.json
  def new
    @garden = Garden.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @garden }
    end
  end

  # GET /gardens/1/edit
  def edit
    @garden = Garden.find(params[:id])
    authorize! :update, @garden
  end

  # POST /gardens
  # POST /gardens.json
  def create
    @garden = Garden.new(params[:garden])
    @garden.user = current_user

    respond_to do |format|
      if @garden.save
        format.html { redirect_to @garden, notice: 'Garden was successfully created.' }
        format.json { render json: @garden, status: :created, location: @garden }
      else
        format.html { render action: "new" }
        format.json { render json: @garden.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /gardens/1
  # PUT /gardens/1.json
  def update
    @garden = Garden.find(params[:id])
    @garden.user = current_user

    respond_to do |format|
      if @garden.update_attributes(params[:garden])
        format.html { redirect_to @garden, notice: 'Garden was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @garden.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gardens/1
  # DELETE /gardens/1.json
  def destroy
    @garden = Garden.find(params[:id])
    authorize! :destroy, @garden
    @garden.destroy

    respond_to do |format|
      format.html { redirect_to gardens_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/helpers/gardens_helper.rb
module GardensHelper
end

app/views/gardens/_form.html.erb
<div class="row">
<div class="span3 offset1">
  <h4>About your Parcel</h4>
</div>
  
</div>
<%= simple_form_for @garden, :html => {:class => 'form-horizontal' } do |f| %>
  <%= f.input :title %>
  <%= f.input :address %>
  <%= f.input :description, :as => :text, :input_html => {
  :placeholder => "Tell Gardeners about amenities,
  closeness to transportation, soil quality, tools need, and parking. Are you a great host? Tell them that too!", :rows => 5,
  :cols => 500 } %>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")), gardens_path, :class => 'btn' %>
  </div>
<% end %>

app/views/gardens/edit.html.erb
<%- model_class = Garden -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/gardens/index.html.erb
<%- model_class = Garden -%>
<div class="row">
  <div class="span12">
    <div class="page-header">
      <h4 class="muted">Turn idle backyards into fresh fruits and
      veggies</h4>
    </div>
  </div>
</div>
<div class="row">
  <div class="span4">
    <%= gmaps("map_options" => { "detect_location" => true,
                                 "center_on_user" => true,
                                 :auto_adjust => true, "zoom" => 6},
                                 "markers" => { "data" => @json }) %>
  </div>
  <div class="span8">
    <table class="table table-striped">
      <thead>
        <tr>
          <h5>Some spaces to garden<h5>
        </tr>
      </thead>
      <tbody>
        <% @gardens.each do |garden| %>
        <tr>
          <td>
            <img src="http://placehold.it/100x70&text=pics+coming!" alt="" />
          </td>
          <td>
              <%= link_to garden.title, garden_path(garden) %>
          </td>
          <td>
            <small><%= garden.neighborhood %></small>
          </td>
          <td>
            <small><%= garden.created_at.strftime("%d %b %Y") %></small>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div> <!-- span8 -->

</div>

app/views/gardens/new.html.erb
<%- model_class = Garden -%>
<div class="page-header">
  <h3>List your garden.</h3>
</div>
<%= render :partial => 'form' %>

app/views/gardens/show.html.erb
<div class="row">
  <div class="span12">
    <div class="page-header">
      <h2><%= @garden.title %> <small> <%= @garden.neighborhood %></small></h2>
    </div>
  </div>
</div>

<div class="row">
  <div class="span8">
    <h3>Description</h3>
    <p><%= @garden.description %></p>
    <h3>Photos</h3>
    <img src="http://placehold.it/300x300&text=photos+coming+soon!" class="img-polaroid">
  </div>
  <div class="span4">
    <div class="well">
      <h5></h5>
      <dl>
        <dt>Want to work on this garden?</dt>
        <dd>Send a message to <%= @garden.user.first_name %></dd> <br />
        <dt>Message</dt>
        <dd><textarea rows="3" placeholder="Ask about the availability of working on the garden"></textarea></dd>
      </dl>
      <%= button_to "Message", new_garden_path,
          :class => "btn disabled", :method => :get, :disabled => "disabled" %>
      <% if current_user %>
        <% if can? :update, @garden %>
          <%= link_to t('.edit', :default => t("helpers.links.edit")), edit_garden_path(@garden), :class => 'btn' %>
        <% end %>
        <% if can? :destroy, @garden %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              garden_path(@garden),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Parcel" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag %>
  </head>
  <body>

    <div class="navbar navbar-static-top">
      <div class="navbar-inner">
        <div class="container">
          <div class="row">
            <div class="span4">
              <a class="brand" href="/">Parcel</a>
            </div>
            <div class="span6">
              <ul class="nav pull-right">
                <li>
                  <%= link_to "how it works", "http://youtu.be/sw_FiKyD4bg?hd=1" %>
                </li>
                <li>
                  <%= link_to "suggest a new idea", "https://github.com/akshatpradhan/parcel/issues" %>
                </li>
                <li>
                  <% if current_user %>
                  <%= link_to "sign out", signout_path, id: "sign_out" %>
                  <% else %>
                  <%= link_to "login/register", "/auth/facebook", id: "sign_in" %>
                  <% end %>
                </li>
              </ul>
            </div>
            <div class="span2">
              <%= button_to "List your space", new_garden_path,
                  :class => "btn btn-primary pull-right", :method => :get %>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="span12">
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p>&copy; Parcel 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
    <%= yield :scripts %>
  </body>
</html>